package presentacion;

import Negocio.BOs.ICarritoBO;
import Negocio.BOs.IPizzaBO;
import Negocio.DTOs.CarritoDTO;
import Negocio.DTOs.DetalleCarritoDTO;
import Negocio.DTOs.PizzaDTO;
import Negocio.Fabrica.FabricaBOs;
import Negocio.excepciones.NegocioException;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import negocio.bos.CarritoBO;
import presentacion.vistas.frmAvisos;

/**
 *
 * @author Brian
 */
public class frmDetallesPizza extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmDetallesPizza.class.getName());
    private int idUsuario;
    private String token;
    PizzaDTO pizza;
    boolean express;

    public frmDetallesPizza() {
        initComponents();
    }

    public void cargarInformacionPizza(PizzaDTO pizza, int idUsuario) {
        this.idUsuario = idUsuario;
        this.pizza = pizza;

        lblDescripcionPizza.setText(pizza.getDescripcion());
        lblTituloPïzza.setText(pizza.getNombre());
        lblImagenPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + pizza.getRutaImagen())));

        jrbChica.setVisible(false);
        jrbMediana.setVisible(false);
        jrbGrande.setVisible(false);

        int cantidadDeTamanios = pizza.getTamanios().size();

        if (cantidadDeTamanios > 0) {
            jrbChica.setText(pizza.getTamanios().get(0) + ": $" + pizza.getPrecios().get(0) + " MXN");
            jrbChica.setVisible(true);
        }

        if (cantidadDeTamanios > 1) {
            jrbMediana.setText(pizza.getTamanios().get(1) + ": $" + pizza.getPrecios().get(1) + " MXN");
            jrbMediana.setVisible(true);
        }

        if (cantidadDeTamanios > 2) {
            jrbGrande.setText(pizza.getTamanios().get(2) + ": $" + pizza.getPrecios().get(2) + " MXN");
            jrbGrande.setVisible(true);
        }
    }

    public void cargarInformacionPizzaExpress(PizzaDTO pizza, String token) {
        this.pizza = pizza;
        this.token = token;
        this.express = true;

        txtNota.setVisible(false);
        jSeparator1.setVisible(false);
        jLabel8.setVisible(false);

        lblDescripcionPizza.setText(pizza.getDescripcion());
        lblTituloPïzza.setText(pizza.getNombre());
        lblImagenPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + pizza.getRutaImagen())));

        jrbChica.setVisible(false);
        jrbMediana.setVisible(false);
        jrbGrande.setVisible(false);

        int cantidadDeTamanios = pizza.getTamanios().size();

        if (cantidadDeTamanios > 0) {
            jrbChica.setText(pizza.getTamanios().get(0) + ": $" + pizza.getPrecios().get(0) + " MXN");
            jrbChica.setVisible(true);
        }

        if (cantidadDeTamanios > 1) {
            jrbMediana.setText(pizza.getTamanios().get(1) + ": $" + pizza.getPrecios().get(1) + " MXN");
            jrbMediana.setVisible(true);
        }

        if (cantidadDeTamanios > 2) {
            jrbGrande.setText(pizza.getTamanios().get(2) + ": $" + pizza.getPrecios().get(2) + " MXN");
            jrbGrande.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTamanios = new javax.swing.ButtonGroup();
        panLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTituloLogo = new javax.swing.JLabel();
        panPizzas = new javax.swing.JPanel();
        lblImagenPizza = new javax.swing.JLabel();
        lblTituloPïzza = new javax.swing.JLabel();
        lblIngredientesPizza = new javax.swing.JLabel();
        btnAnadir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jrbChica = new javax.swing.JRadioButton();
        jrbMediana = new javax.swing.JRadioButton();
        jrbGrande = new javax.swing.JRadioButton();
        txtNota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblDescripcionPizza = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        panLogo.setBackground(new java.awt.Color(237, 96, 66));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpeg"))); // NOI18N
        lblLogo.setText("jLabel1");

        lblTituloLogo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 100)); // NOI18N
        lblTituloLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLogo.setText("PAPIZZA");

        javax.swing.GroupLayout panLogoLayout = new javax.swing.GroupLayout(panLogo);
        panLogo.setLayout(panLogoLayout);
        panLogoLayout.setHorizontalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panLogoLayout.setVerticalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo)
                    .addComponent(lblTituloLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panPizzas.setBackground(new java.awt.Color(255, 232, 216));

        lblImagenPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTituloPïzza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblIngredientesPizza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAnadir.setBackground(new java.awt.Color(255, 92, 56));
        btnAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnadirMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("+Añadir");

        javax.swing.GroupLayout btnAnadirLayout = new javax.swing.GroupLayout(btnAnadir);
        btnAnadir.setLayout(btnAnadirLayout);
        btnAnadirLayout.setHorizontalGroup(
            btnAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        btnAnadirLayout.setVerticalGroup(
            btnAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        btnVolver.setBackground(new java.awt.Color(255, 92, 56));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Volver");

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        grupoTamanios.add(jrbChica);
        jrbChica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbChica.setText("Chica");
        jrbChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbChicaActionPerformed(evt);
            }
        });

        grupoTamanios.add(jrbMediana);
        jrbMediana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbMediana.setText("Mediana");

        grupoTamanios.add(jrbGrande);
        jrbGrande.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbGrande.setText("Grande");

        txtNota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNota.setForeground(java.awt.Color.gray);
        txtNota.setText("Ingrese la nota");
        txtNota.setToolTipText("");
        txtNota.setBorder(null);
        txtNota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNotaFocusLost(evt);
            }
        });
        txtNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNotaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNotaMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel8.setText("Nota:");

        lblDescripcionPizza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panPizzasLayout = new javax.swing.GroupLayout(panPizzas);
        panPizzas.setLayout(panPizzasLayout);
        panPizzasLayout.setHorizontalGroup(
            panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPizzasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(panPizzasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblImagenPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIngredientesPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblDescripcionPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloPïzza, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbMediana)
                    .addComponent(jrbChica)
                    .addComponent(jrbGrande))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPizzasLayout.setVerticalGroup(
            panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPizzasLayout.createSequentialGroup()
                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPizzasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagenPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPizzasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTituloPïzza, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcionPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jrbChica)
                        .addGap(18, 18, 18)
                        .addComponent(jrbMediana)
                        .addGap(18, 18, 18)
                        .addComponent(jrbGrande)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIngredientesPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPizzasLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(panPizzasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panPizzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panPizzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseClicked
        String tamanioSeleccionado = null;
        ICarritoBO carrito = FabricaBOs.obtenerCarrito();

        int cantidadDeTamanios = pizza.getTamanios().size();
        if (jrbChica.isSelected()) {
            tamanioSeleccionado = pizza.getTamanios().get(0);
        } else if (jrbMediana.isSelected()) {
            tamanioSeleccionado = pizza.getTamanios().get(1);
        } else if (jrbGrande.isSelected()) {
            tamanioSeleccionado = pizza.getTamanios().get(2);
        }
        if (tamanioSeleccionado == null) {
            frmAvisos aviso = new frmAvisos("Por favor selecciona un tamaño");
            aviso.setVisible(true);
            return;
        }

        IPizzaBO pizzita = FabricaBOs.obtenerProductos();
        try {
            ArrayList<PizzaDTO> pizzasFil = pizzita.agruparPizzasPorNombre();
            Map<String, Integer> mapaIds = pizza.getIdsPorTamanio();
            int idPizza = mapaIds.get(tamanioSeleccionado);

            String nota;

            if (txtNota.getText().equals("Ingrese la nota")) {
                nota = "";
            } else {
                nota = txtNota.getText();
            }

            if (express) {
                if (token == null || token.isEmpty()) {
                    throw new NegocioException("Token inválido");
                }
                carrito.agregarProductoExpress(token, idPizza, tamanioSeleccionado, 1, nota);
                frmCarrito pantallaCarrito = new frmCarrito(token);
                pantallaCarrito.setVisible(true);
                this.dispose();
            } else {
                carrito.agregarProducto(idUsuario, idPizza, tamanioSeleccionado, 1, nota);
                frmCarrito pantallaCarrito = new frmCarrito(idUsuario);
                pantallaCarrito.setVisible(true);
                this.dispose();
            }

        } catch (NegocioException ex) {
            System.getLogger(frmDetallesPizza.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnAnadirMouseClicked

    private void btnAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseEntered
        btnAnadir.setBackground(Color.decode("#E82F07"));
    }//GEN-LAST:event_btnAnadirMouseEntered

    private void btnAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseExited
        btnAnadir.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnAnadirMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(Color.decode("#E82F07"));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnVolverMouseExited

    private void txtNotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotaFocusGained
        if (txtNota.getText().equals("Ingrese la nota")) {
            txtNota.setText("");
            txtNota.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNotaFocusGained

    private void txtNotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotaFocusLost
        if (txtNota.getText().isEmpty()) {
            txtNota.setText("Ingrese la nota");
            txtNota.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNotaFocusLost

    private void txtNotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNotaMousePressed

    }//GEN-LAST:event_txtNotaMousePressed

    private void txtNotaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNotaMouseReleased

    }//GEN-LAST:event_txtNotaMouseReleased

    private void jrbChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbChicaActionPerformed

    }//GEN-LAST:event_jrbChicaActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        if (express) {
            frmCatalogo catalogo = new frmCatalogo(express);
            catalogo.setVisible(true);
            this.dispose();
        } else {
            frmCatalogo catalogo = new frmCatalogo(idUsuario);
            catalogo.setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_btnVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmDetallesPizza().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAnadir;
    private javax.swing.JPanel btnVolver;
    private javax.swing.ButtonGroup grupoTamanios;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrbChica;
    private javax.swing.JRadioButton jrbGrande;
    private javax.swing.JRadioButton jrbMediana;
    private javax.swing.JLabel lblDescripcionPizza;
    private javax.swing.JLabel lblImagenPizza;
    private javax.swing.JLabel lblIngredientesPizza;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloLogo;
    private javax.swing.JLabel lblTituloPïzza;
    private javax.swing.JPanel panLogo;
    private javax.swing.JPanel panPizzas;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
}
