package presentacion;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import persistencia.dominio.Pizza;
import presentacion.vistas.panTarjetaPizza;
import Negocio.BOs.IPedidoBO;
import Negocio.BOs.PedidoBO;
import Negocio.DTOs.PedidoDetalleDTO;
import Negocio.DTOs.PedidoTablaDTO;
import Negocio.Fabrica.FabricaBOs;
import Negocio.excepciones.NegocioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.daos.PedidoDAO; // tu implementación real
import javax.swing.table.DefaultTableModel;
import persistencia.conexion.ConexionBD;
import persistencia.conexion.IConexionBD;

/**
 *
 * @author Brian
 */
public class frmEmpleados extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmEmpleados.class.getName());

    private IPedidoBO pedidoBO;

    private List<PedidoTablaDTO> listaPedidosActual = new ArrayList<>();

    public frmEmpleados() {
        initComponents();

        btnCambiarEstado.setEnabled(false);

        tablaPedidos.getSelectionModel().addListSelectionListener(e -> validarBoton());

        pedidoBO = FabricaBOs.crearPedidoBO();

        cargarTabla();
    }

    private void validarBoton() {
        if (listaPedidosActual == null || tablaPedidos.getSelectedRow() == -1) {
            btnCambiarEstado.setEnabled(false);
            return;
        }

        int fila = tablaPedidos.getSelectedRow();
        PedidoTablaDTO pedido = listaPedidosActual.get(fila);
        String estado = pedido.getEstado();

        if (estado.equals("PENDIENTE") || estado.equals("LISTO")) {
            btnCambiarEstado.setEnabled(true);
        } else {
            btnCambiarEstado.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        panLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTituloLogo = new javax.swing.JLabel();
        panPizzas = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        btnCambiarEstado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnDetalles = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        panLogo.setBackground(new java.awt.Color(237, 96, 66));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpeg"))); // NOI18N
        lblLogo.setText("jLabel1");

        lblTituloLogo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 100)); // NOI18N
        lblTituloLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLogo.setText("PAPIZZA");

        javax.swing.GroupLayout panLogoLayout = new javax.swing.GroupLayout(panLogo);
        panLogo.setLayout(panLogoLayout);
        panLogoLayout.setHorizontalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panLogoLayout.setVerticalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo)
                    .addComponent(lblTituloLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        panPizzas.setBackground(new java.awt.Color(255, 232, 216));

        txtBuscador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscador.setForeground(java.awt.Color.gray);
        txtBuscador.setText("Buscar por nombre o teléfono");
        txtBuscador.setToolTipText("");
        txtBuscador.setBorder(null);
        txtBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusLost(evt);
            }
        });
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscadorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtBuscadorMouseReleased(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        btnCambiarEstado.setBackground(new java.awt.Color(44, 44, 44));
        btnCambiarEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarEstadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCambiarEstadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCambiarEstadoMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cambiar Estado");

        javax.swing.GroupLayout btnCambiarEstadoLayout = new javax.swing.GroupLayout(btnCambiarEstado);
        btnCambiarEstado.setLayout(btnCambiarEstadoLayout);
        btnCambiarEstadoLayout.setHorizontalGroup(
            btnCambiarEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCambiarEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCambiarEstadoLayout.setVerticalGroup(
            btnCambiarEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCambiarEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDetalles.setBackground(new java.awt.Color(44, 44, 44));
        btnDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetallesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetallesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetallesMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Detalles");

        javax.swing.GroupLayout btnDetallesLayout = new javax.swing.GroupLayout(btnDetalles);
        btnDetalles.setLayout(btnDetallesLayout);
        btnDetallesLayout.setHorizontalGroup(
            btnDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnDetallesLayout.setVerticalGroup(
            btnDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaPedidos.setBackground(new java.awt.Color(255, 227, 227));
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Cliente", "Teléfono", "Fecha - Hora", "Total", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaPedidos);

        javax.swing.GroupLayout panPizzasLayout = new javax.swing.GroupLayout(panPizzas);
        panPizzas.setLayout(panPizzasLayout);
        panPizzasLayout.setHorizontalGroup(
            panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPizzasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
                    .addGroup(panPizzasLayout.createSequentialGroup()
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        panPizzasLayout.setVerticalGroup(
            panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPizzasLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnCambiarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panPizzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusGained
        if (txtBuscador.getText().equals("Buscar por nombre o teléfono")) {
            txtBuscador.setText("");
            txtBuscador.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtBuscadorFocusGained

    private void txtBuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusLost
        if (txtBuscador.getText().isEmpty()) {
            txtBuscador.setText("Buscar por nombre o teléfono");
            txtBuscador.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscadorFocusLost

    private void txtBuscadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMousePressed

    }//GEN-LAST:event_txtBuscadorMousePressed

    private void txtBuscadorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMouseReleased

    }//GEN-LAST:event_txtBuscadorMouseReleased

    private void btnCambiarEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarEstadoMouseClicked
        cambiarEstado();
    }//GEN-LAST:event_btnCambiarEstadoMouseClicked

    private void btnCambiarEstadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarEstadoMouseEntered
        btnCambiarEstado.setBackground(Color.decode("#525252"));
    }//GEN-LAST:event_btnCambiarEstadoMouseEntered

    private void btnCambiarEstadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarEstadoMouseExited
        btnCambiarEstado.setBackground(Color.decode("#2c2c2c"));
    }//GEN-LAST:event_btnCambiarEstadoMouseExited

    private void btnDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseClicked
        try {
            int fila = tablaPedidos.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Selecciona un pedido");
                return;
            }

            PedidoTablaDTO pedidoSeleccionado = listaPedidosActual.get(fila);
            int idPedido = pedidoSeleccionado.getIdPedido(); // aquí ya tienes el ID

            PedidoDetalleDTO detalle = pedidoBO.obtenerDetallePedido(idPedido);

            frmDetallePedido dialog = new frmDetallePedido(this, true, detalle);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (NegocioException ex) {
            Logger.getLogger(frmEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDetallesMouseClicked

    private void btnDetallesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseEntered
        btnDetalles.setBackground(Color.decode("#525252"));
    }//GEN-LAST:event_btnDetallesMouseEntered

    private void btnDetallesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseExited
        btnDetalles.setBackground(Color.decode("#2c2c2c"));
    }//GEN-LAST:event_btnDetallesMouseExited

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        String texto = txtBuscador.getText().trim();

        try {
            if (texto.isEmpty() || texto.equals("Buscar por nombre o teléfono")) {
                llenarTabla(pedidoBO.obtenerPedidosTabla());
            } else {
                llenarTabla(pedidoBO.obtenerPedidosFiltrados(texto));
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al filtrar pedidos");
        }

    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void cargarTabla() {

        try {

            List<PedidoTablaDTO> pedidos = pedidoBO.obtenerPedidosTabla();
            llenarTabla(pedidos);

        } catch (NegocioException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar pedidos: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void llenarTabla(List<PedidoTablaDTO> pedidos) {

        this.listaPedidosActual = pedidos;

        DefaultTableModel modelo = (DefaultTableModel) tablaPedidos.getModel();
        modelo.setRowCount(0);

        for (PedidoTablaDTO p : pedidos) {

            Object[] fila = {
                p.getFolio(),
                p.getCliente(),
                p.getTelefono(),
                p.getFechaHora().format(
                java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")
                ),
                p.getTotal(),
                p.getEstado(),};

            modelo.addRow(fila);
        }
    }

    private void cambiarEstado() {

        int fila = tablaPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un pedido");
            return;
        }

        PedidoTablaDTO pedidoSeleccionado = listaPedidosActual.get(fila);
        int idPedido = pedidoSeleccionado.getIdPedido();
        String estadoActual = pedidoSeleccionado.getEstado();

        // Si ya es estado final no permitir cambios
        if (estadoActual.equals("ENTREGADO")
                || estadoActual.equals("CANCELADO")
                || estadoActual.equals("NO ENTREGADO")) {

            JOptionPane.showMessageDialog(this,
                    "Este pedido ya está finalizado y no puede modificarse.");
            return;
        }

        String[] estadosDisponibles;

        if (estadoActual.equals("PENDIENTE")) {
            estadosDisponibles = new String[]{"LISTO", "CANCELADO"};
        } else if (estadoActual.equals("LISTO")) {
            estadosDisponibles = new String[]{"ENTREGADO", "CANCELADO"};
        } else {
            return;
        }

        String nuevoEstado = (String) JOptionPane.showInputDialog(
                this,
                "Estado actual: " + estadoActual + "\nSelecciona el nuevo estado:",
                "Cambiar Estado",
                JOptionPane.QUESTION_MESSAGE,
                null,
                estadosDisponibles,
                estadosDisponibles[0]
        );

        if (nuevoEstado == null) {
            return;
        }

        // Confirmación si cancela
        if (nuevoEstado.equals("CANCELADO")) {
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Estás seguro de cancelar este pedido?",
                    "Confirmar cancelación",
                    JOptionPane.YES_NO_OPTION
            );
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }
        }

        try {
            // Antes de marcar ENTREGADO 
            if (nuevoEstado.equals("ENTREGADO")) {

                // Registrar el pago (puedes personalizar según tu BO/DAO)
                int confirmarPago = JOptionPane.showConfirmDialog(
                        this,
                        "¿Se ha recibido el pago del pedido?",
                        "Confirmar pago",
                        JOptionPane.YES_NO_OPTION
                );
                if (confirmarPago != JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(this,
                            "No se puede entregar un pedido sin registrar el pago.");
                    return;
                }

                // Si es pedido EXPRESS, pedir folio y PIN
                if (pedidoSeleccionado.getTipo().equalsIgnoreCase("EXPRESS")) {
                    String folio = JOptionPane.showInputDialog(this, "Ingresa el folio del cliente:");
                    if (folio == null || folio.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Folio requerido para pedido EXPRESS.");
                        return;
                    }
                    String pin = JOptionPane.showInputDialog(this, "Ingresa el PIN de seguridad:");
                    if (pin == null || pin.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "PIN requerido para pedido EXPRESS.");
                        return;
                    }

                    // Validar folio y PIN con la base de datos
                    boolean valido = pedidoBO.validarFolioYPIN(idPedido, folio, pin);
                    if (!valido) {
                        JOptionPane.showMessageDialog(this,
                                "Folio o PIN incorrectos, no se puede entregar el pedido.");
                        return;
                    }
                }
            }

            // Cambiar estado en la base de datos
            pedidoBO.cambiarEstado(idPedido, nuevoEstado);
            JOptionPane.showMessageDialog(this, "Estado actualizado correctamente.");
            cargarTabla();

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmEmpleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCambiarEstado;
    private javax.swing.JPanel btnDetalles;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloLogo;
    private javax.swing.JPanel panLogo;
    private javax.swing.JPanel panPizzas;
    private javax.swing.JTable tablaPedidos;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
