package presentacion;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import persistencia.dominio.Pizza;
import presentacion.vistas.panTarjetaPizza;

/**
 *
 * @author Brian
 */
public class frmMisPedidos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMisPedidos.class.getName());

    public frmMisPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTituloLogo = new javax.swing.JLabel();
        panNavegacion = new javax.swing.JPanel();
        btnInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnMispedidos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPE = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panPizzas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        btnCancelar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        txtAnio = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAnio1 = new javax.swing.JTextField();
        txtMes1 = new javax.swing.JTextField();
        txtDia1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        panLogo.setBackground(new java.awt.Color(237, 96, 66));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpeg"))); // NOI18N
        lblLogo.setText("jLabel1");

        lblTituloLogo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 100)); // NOI18N
        lblTituloLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLogo.setText("PAPIZZA");

        panNavegacion.setBackground(new java.awt.Color(255, 92, 56));
        panNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(255, 92, 56));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panNavegacion.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -2, 100, 60));

        btnActualizar.setBackground(new java.awt.Color(255, 92, 56));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        panNavegacion.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, -4, -1, 70));

        btnCarrito.setBackground(new java.awt.Color(255, 92, 56));
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarritoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCarritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCarritoMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Carrito");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnCarritoLayout = new javax.swing.GroupLayout(btnCarrito);
        btnCarrito.setLayout(btnCarritoLayout);
        btnCarritoLayout.setHorizontalGroup(
            btnCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        btnCarritoLayout.setVerticalGroup(
            btnCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCarritoLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        panNavegacion.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, -4, -1, 70));

        btnMispedidos.setBackground(new java.awt.Color(255, 92, 56));
        btnMispedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMispedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMispedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMispedidosMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mis pedidos");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnMispedidosLayout = new javax.swing.GroupLayout(btnMispedidos);
        btnMispedidos.setLayout(btnMispedidosLayout);
        btnMispedidosLayout.setHorizontalGroup(
            btnMispedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnMispedidosLayout.setVerticalGroup(
            btnMispedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMispedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        panNavegacion.add(btnMispedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1069, -6, 130, 70));

        btnPE.setBackground(new java.awt.Color(255, 92, 56));
        btnPE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPEMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pedido Express");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnPELayout = new javax.swing.GroupLayout(btnPE);
        btnPE.setLayout(btnPELayout);
        btnPELayout.setHorizontalGroup(
            btnPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnPELayout.setVerticalGroup(
            btnPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPELayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panNavegacion.add(btnPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 2, 150, 60));

        javax.swing.GroupLayout panLogoLayout = new javax.swing.GroupLayout(panLogo);
        panLogo.setLayout(panLogoLayout);
        panLogoLayout.setHorizontalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLayout.createSequentialGroup()
                .addGroup(panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panLogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTituloLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panLogoLayout.setVerticalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo)
                    .addComponent(lblTituloLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(panNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panPizzas.setBackground(new java.awt.Color(255, 232, 216));

        tablaPedidos.setBackground(new java.awt.Color(255, 227, 227));
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Cliente", "Producto", "Fecha - Hora", "Total", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaPedidos);

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmbTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtAnio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAnio.setForeground(java.awt.Color.gray);
        txtAnio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnio.setText("YYYY");
        txtAnio.setToolTipText("");
        txtAnio.setBorder(null);
        txtAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnioFocusLost(evt);
            }
        });
        txtAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAnioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtAnioMouseReleased(evt);
            }
        });
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });

        txtMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMes.setForeground(java.awt.Color.gray);
        txtMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMes.setText("MM");
        txtMes.setToolTipText("");
        txtMes.setBorder(null);
        txtMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesFocusLost(evt);
            }
        });
        txtMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMesMouseReleased(evt);
            }
        });
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });

        txtDia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDia.setForeground(java.awt.Color.gray);
        txtDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDia.setText("DD");
        txtDia.setToolTipText("");
        txtDia.setBorder(null);
        txtDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaFocusLost(evt);
            }
        });
        txtDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDiaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDiaMouseReleased(evt);
            }
        });
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Fecha Inicio");

        txtAnio1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAnio1.setForeground(java.awt.Color.gray);
        txtAnio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnio1.setText("YYYY");
        txtAnio1.setToolTipText("");
        txtAnio1.setBorder(null);
        txtAnio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnio1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnio1FocusLost(evt);
            }
        });
        txtAnio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAnio1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtAnio1MouseReleased(evt);
            }
        });
        txtAnio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnio1KeyTyped(evt);
            }
        });

        txtMes1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMes1.setForeground(java.awt.Color.gray);
        txtMes1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMes1.setText("MM");
        txtMes1.setToolTipText("");
        txtMes1.setBorder(null);
        txtMes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMes1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMes1FocusLost(evt);
            }
        });
        txtMes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMes1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMes1MouseReleased(evt);
            }
        });
        txtMes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMes1KeyTyped(evt);
            }
        });

        txtDia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDia1.setForeground(java.awt.Color.gray);
        txtDia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDia1.setText("DD");
        txtDia1.setToolTipText("");
        txtDia1.setBorder(null);
        txtDia1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDia1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDia1FocusLost(evt);
            }
        });
        txtDia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDia1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDia1MouseReleased(evt);
            }
        });
        txtDia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDia1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDia1KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Fecha Fin");

        javax.swing.GroupLayout panPizzasLayout = new javax.swing.GroupLayout(panPizzas);
        panPizzas.setLayout(panPizzasLayout);
        panPizzasLayout.setHorizontalGroup(
            panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPizzasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(panPizzasLayout.createSequentialGroup()
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(panPizzasLayout.createSequentialGroup()
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(panPizzasLayout.createSequentialGroup()
                                .addComponent(txtDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnio1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        panPizzasLayout.setVerticalGroup(
            panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPizzasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPizzasLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPizzasLayout.createSequentialGroup()
                        .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panPizzasLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnio1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panPizzasLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panPizzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panPizzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        btnInicio.setBackground(Color.decode("#E82F07"));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        btnInicio.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        btnActualizar.setBackground(Color.decode("#E82F07"));
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        btnActualizar.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnCarritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseEntered
        btnCarrito.setBackground(Color.decode("#E82F07"));
    }//GEN-LAST:event_btnCarritoMouseEntered

    private void btnCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseExited
        btnCarrito.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnCarritoMouseExited

    private void btnMispedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMispedidosMouseEntered
        btnMispedidos.setBackground(Color.decode("#E82F07"));
    }//GEN-LAST:event_btnMispedidosMouseEntered

    private void btnMispedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMispedidosMouseExited
        btnMispedidos.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnMispedidosMouseExited

    private void btnPEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPEMouseEntered
        btnPE.setBackground(Color.decode("#E82F07"));
    }//GEN-LAST:event_btnPEMouseEntered

    private void btnPEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPEMouseExited
        btnPE.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnPEMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setBackground(Color.decode("#525252"));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setBackground(Color.decode("#2c2c2c"));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void txtAnioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusGained
        if (txtAnio.getText().equals("YYYY")) {
            txtAnio.setText("");
            txtAnio.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtAnioFocusGained

    private void txtAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusLost
        if (txtAnio.getText().isEmpty()) {
            txtAnio.setText("YYYY");
            txtAnio.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtAnioFocusLost

    private void txtAnioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioMousePressed

    private void txtAnioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioMouseReleased

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        if (txtAnio.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAnioKeyTyped

    private void txtMesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesFocusGained
        if (txtMes.getText().equals("MM")) {
            txtMes.setText("");
            txtMes.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMesFocusGained

    private void txtMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesFocusLost
        if (txtMes.getText().isEmpty()) {
            txtMes.setText("MM");
            txtMes.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtMesFocusLost

    private void txtMesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesMousePressed

    private void txtMesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesMouseReleased

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        if (txtMes.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtDiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaFocusGained
        if (txtDia.getText().equals("DD")) {
            txtDia.setText("");
            txtDia.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtDiaFocusGained

    private void txtDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaFocusLost
        if (txtDia.getText().isEmpty()) {
            txtDia.setText("DD");
            txtDia.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDiaFocusLost

    private void txtDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaMousePressed

    private void txtDiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaMouseReleased

    private void txtDiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyPressed

    }//GEN-LAST:event_txtDiaKeyPressed

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        if (txtDia.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtAnio1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnio1FocusGained
        if (txtAnio1.getText().equals("YYYY")) {
            txtAnio1.setText("");
            txtAnio1.setForeground(Color.black);
        }    }//GEN-LAST:event_txtAnio1FocusGained

    private void txtAnio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnio1FocusLost
        if (txtAnio1.getText().isEmpty()) {
            txtAnio1.setText("YYYY");
            txtAnio1.setForeground(Color.gray);
        }    }//GEN-LAST:event_txtAnio1FocusLost

    private void txtAnio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnio1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnio1MousePressed

    private void txtAnio1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnio1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnio1MouseReleased

    private void txtAnio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnio1KeyTyped
        if (txtAnio1.getText().length() >= 4) {
            evt.consume();
        }    }//GEN-LAST:event_txtAnio1KeyTyped

    private void txtMes1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMes1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMes1FocusGained

    private void txtMes1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMes1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMes1FocusLost

    private void txtMes1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMes1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMes1MousePressed

    private void txtMes1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMes1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMes1MouseReleased

    private void txtMes1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMes1KeyTyped
        if (txtMes1.getText().length() >= 2) {
            evt.consume();
        }    }//GEN-LAST:event_txtMes1KeyTyped

    private void txtDia1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDia1FocusGained
        if (txtDia1.getText().isEmpty()) {
            txtDia1.setText("DD");
            txtDia1.setForeground(Color.gray);
        }    }//GEN-LAST:event_txtDia1FocusGained

    private void txtDia1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDia1FocusLost
        if (txtDia1.getText().isEmpty()) {
            txtDia1.setText("DD");
            txtDia1.setForeground(Color.gray);
        }    }//GEN-LAST:event_txtDia1FocusLost

    private void txtDia1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDia1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDia1MousePressed

    private void txtDia1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDia1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDia1MouseReleased

    private void txtDia1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDia1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDia1KeyPressed

    private void txtDia1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDia1KeyTyped
        if (txtDia1.getText().length() >= 2) {
            evt.consume();
        }    }//GEN-LAST:event_txtDia1KeyTyped

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        frmCatalogo catalogo = new frmCatalogo();
        catalogo.setVisible(true);
        this.dispose();
     }//GEN-LAST:event_btnInicioMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseClicked
        frmCarrito carrito = new frmCarrito();
        carrito.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarritoMouseClicked

    private void btnMispedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMispedidosMouseClicked

    }//GEN-LAST:event_btnMispedidosMouseClicked

    private void btnPEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPEMouseClicked
        frmPedidoExpress pe = new frmPedidoExpress();
        pe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMisPedidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnCarrito;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnMispedidos;
    private javax.swing.JPanel btnPE;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloLogo;
    private javax.swing.JPanel panLogo;
    private javax.swing.JPanel panNavegacion;
    private javax.swing.JPanel panPizzas;
    private javax.swing.JTable tablaPedidos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAnio1;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDia1;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtMes1;
    // End of variables declaration//GEN-END:variables
}
