/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.vistas;

import Negocio.BOs.IPizzaBO;
import Negocio.BOs.PizzaBO;
import Negocio.DTOs.PizzaDTO;
import Negocio.DTOs.PizzaProductoDTO;
import Negocio.excepciones.NegocioException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class panProductosTarjetas extends javax.swing.JPanel {
    private PizzaProductoDTO pizza;
    private IPizzaBO pizzaBO;
    /**
     * Creates new form panProductosTarjetas
     */
    public panProductosTarjetas(PizzaProductoDTO pizza, IPizzaBO pizzaBO) {
        initComponents();
        this.pizza = pizza;
        this.pizzaBO = pizzaBO;
        
        lblNombrePizza.setText(pizza.getNombre());
        lblEstadoPizza.setText(pizza.getEstado().toString());
        
        if (pizza.getRutaImagen() != null && !pizza.getRutaImagen().isEmpty()) {
            java.net.URL url = getClass().getResource("/" + pizza.getRutaImagen());
            if (url != null) {
                imgPizza.setIcon(new ImageIcon(url));
                imgPizza.setText("");
            } else {
                imgPizza.setText("Imagen no encontrada");
                imgPizza.setIcon(null);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgPizza = new javax.swing.JLabel();
        lblNombrePizza = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEstadoPizza = new javax.swing.JLabel();
        txtPrecioAct = new javax.swing.JTextField();
        btnActualizarPrecio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblPrecioPizza = new javax.swing.JLabel();
        btnCambiarEstado = new javax.swing.JButton();
        btnMediana = new javax.swing.JButton();
        btnGrande = new javax.swing.JButton();
        btnChica = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        imgPizza.setText("jLabel2");

        lblNombrePizza.setBackground(new java.awt.Color(255, 255, 255));
        lblNombrePizza.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNombrePizza.setForeground(new java.awt.Color(204, 102, 0));
        lblNombrePizza.setText("Nombre de la Pizza");

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 141, 0));
        jLabel1.setText("Precio actual de la pizza:");

        lblEstadoPizza.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        lblEstadoPizza.setForeground(new java.awt.Color(225, 141, 0));
        lblEstadoPizza.setText("estado de la pizza");

        txtPrecioAct.setFont(new java.awt.Font("Segoe UI Variable", 0, 16)); // NOI18N

        btnActualizarPrecio.setBackground(new java.awt.Color(255, 213, 153));
        btnActualizarPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizarPrecio.setText("Actualizar Precio");
        btnActualizarPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPrecioMouseClicked(evt);
            }
        });
        btnActualizarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPrecioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(225, 141, 0));
        jLabel5.setText("ESTADO: ");

        lblPrecioPizza.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        lblPrecioPizza.setForeground(new java.awt.Color(225, 141, 0));
        lblPrecioPizza.setText("$$$");

        btnCambiarEstado.setBackground(new java.awt.Color(255, 213, 153));
        btnCambiarEstado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCambiarEstado.setText("Cambiar Estado");
        btnCambiarEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarEstadoMouseClicked(evt);
            }
        });
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });

        btnMediana.setBackground(new java.awt.Color(255, 223, 183));
        btnMediana.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnMediana.setText("MEDIANA");
        btnMediana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedianaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMedianaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMedianaMouseReleased(evt);
            }
        });
        btnMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedianaActionPerformed(evt);
            }
        });

        btnGrande.setBackground(new java.awt.Color(255, 223, 183));
        btnGrande.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnGrande.setText("GRANDE");
        btnGrande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrandeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGrandeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGrandeMouseReleased(evt);
            }
        });
        btnGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrandeActionPerformed(evt);
            }
        });

        btnChica.setBackground(new java.awt.Color(255, 223, 183));
        btnChica.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnChica.setText("CHICA");
        btnChica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChicaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnChicaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChicaMouseReleased(evt);
            }
        });
        btnChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(imgPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecioPizza))
                    .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstadoPizza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrecioAct, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarPrecio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChica, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombrePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombrePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChica, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPrecioPizza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioAct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblEstadoPizza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPrecioActionPerformed
        if(!txtPrecioAct.getText().trim().matches("\\d+(\\.\\d{1,2})?")){
            JOptionPane.showMessageDialog(this, "El precio debe contener solo numeros");
            return;
        }
        
        try{
            double nuevoPrecio = Double.parseDouble(txtPrecioAct.getText());
            
            pizzaBO.actualizarPrecioPizza(pizza.getNombre(), pizza.getTamanio(), nuevoPrecio);
            
            pizza.setPrecio(nuevoPrecio);
            lblPrecioPizza.setText("$" + nuevoPrecio);
            
            JOptionPane.showMessageDialog(this, "Precio actualizado correctamente");
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el precio de la pizza");
        }
    }//GEN-LAST:event_btnActualizarPrecioActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void btnMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedianaActionPerformed

    private void btnGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrandeActionPerformed

    private void btnChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChicaActionPerformed

    private void btnChicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChicaMouseClicked
        try{
            PizzaProductoDTO p = pizzaBO.obtenerPizzaPorTamano(pizza.getNombre(), "CHICA");
            
            lblEstadoPizza.setText(p.getEstado().toString());
            lblPrecioPizza.setText("$"+p.getPrecio());
            
            if (p.getRutaImagen() != null && !p.getRutaImagen().isEmpty()) {
                String rutaCorregida = p.getRutaImagen().replace("\\", "/");
                imgPizza.setIcon(new ImageIcon(rutaCorregida));
                imgPizza.setText("");
            }
            
            pizza = p;
        } catch (NegocioException ex) {
            Logger.getLogger(panProductosTarjetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChicaMouseClicked

    private void btnMedianaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedianaMouseClicked
        try{
            PizzaProductoDTO p = pizzaBO.obtenerPizzaPorTamano(pizza.getNombre(), "MEDIANA");
            lblEstadoPizza.setText(p.getEstado().toString());
            lblPrecioPizza.setText("$"+p.getPrecio());
            
            if (p.getRutaImagen() != null && !p.getRutaImagen().isEmpty()) {
                String rutaCorregida = p.getRutaImagen().replace("\\", "/");
                imgPizza.setIcon(new ImageIcon(rutaCorregida));
                imgPizza.setText("");
            }
            
            pizza = p;
        } catch (NegocioException ex) {
            Logger.getLogger(panProductosTarjetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMedianaMouseClicked

    private void btnGrandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrandeMouseClicked
        try{
            PizzaProductoDTO p = pizzaBO.obtenerPizzaPorTamano(pizza.getNombre(), "GRANDE");
            
            lblEstadoPizza.setText(p.getEstado().toString());
            lblPrecioPizza.setText("$"+p.getPrecio());
            
            if (p.getRutaImagen() != null && !p.getRutaImagen().isEmpty()) {
                String rutaCorregida = p.getRutaImagen().replace("\\", "/");
                imgPizza.setIcon(new ImageIcon(rutaCorregida));
                imgPizza.setText("");
            }
            
            pizza = p;
        } catch (NegocioException ex) {
            Logger.getLogger(panProductosTarjetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGrandeMouseClicked

    private void btnActualizarPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPrecioMouseClicked
        if(!txtPrecioAct.getText().matches("[0-9]+")){
            JOptionPane.showConfirmDialog(this, "Solo se pueden ingresar numeros", "Precio inválido", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarPrecioMouseClicked

    private void btnChicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChicaMousePressed
        btnChica.setBackground(new Color(255, 170, 107));
        btnMediana.setBackground(new Color(255,223,183));
        btnGrande.setBackground(new Color(255,223,183));
    }//GEN-LAST:event_btnChicaMousePressed

    private void btnMedianaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedianaMousePressed
        btnMediana.setBackground(new Color(255, 170, 107));
        btnChica.setBackground(new Color(255,223,183));
        btnGrande.setBackground(new Color(255,223,183));
    }//GEN-LAST:event_btnMedianaMousePressed

    private void btnGrandeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrandeMousePressed
        btnGrande.setBackground(new Color(255, 170, 107));
        btnChica.setBackground(new Color(255,223,183));
        btnMediana.setBackground(new Color(255,223,183));
    }//GEN-LAST:event_btnGrandeMousePressed

    private void btnChicaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChicaMouseReleased
        
    }//GEN-LAST:event_btnChicaMouseReleased

    private void btnMedianaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedianaMouseReleased

    }//GEN-LAST:event_btnMedianaMouseReleased

    private void btnGrandeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrandeMouseReleased

    }//GEN-LAST:event_btnGrandeMouseReleased

    private void btnCambiarEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarEstadoMouseClicked
        try{
            pizzaBO.actualizarEstadoPizza(pizza.getIdPizza());
            pizza = pizzaBO.obtenerPizzaPorTamano(pizza.getNombre(), pizza.getTamanio());
            
            
            lblEstadoPizza.setText(pizza.getEstado().toString());
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el estado");
        }
    }//GEN-LAST:event_btnCambiarEstadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPrecio;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnChica;
    private javax.swing.JButton btnGrande;
    private javax.swing.JButton btnMediana;
    private javax.swing.JLabel imgPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoPizza;
    private javax.swing.JLabel lblNombrePizza;
    private javax.swing.JLabel lblPrecioPizza;
    private javax.swing.JTextField txtPrecioAct;
    // End of variables declaration//GEN-END:variables
}
