/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import persistencia.dominio.DetallePedido;
import persistencia.dominio.Pedido;
import presentacion.frmCarrito;

/**
 *
 * @author Brian
 */
public class panPedido extends javax.swing.JPanel {

    private DetallePedido detalle;
    private frmCarrito carrito;

    /**
     * Creates new form panPedido
     *
     * @param detalle
     */
    public panPedido(DetallePedido detalle, frmCarrito carrito) {
        initComponents();
        this.detalle = detalle;
        this.carrito = carrito;
        setDatosPizza();
        cargarInfo();
        setPreferredSize(new Dimension(600, 200));
        setMaximumSize(new Dimension(Integer.MAX_VALUE, 200));
    }

    public void setDatosPizza() {

        // Aquí cambiamos el texto
        lblNombrePizza.setText(detalle.getPizza().getNombre());

        switch (detalle.getPizza().getNombre()) {
            case "La Papi-Margarita":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papiPizza.jpg")));
                break;
            case "Pepperoni Supreme":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pepperoni.jpg")));
                break;
            case "Hawaiian Punch":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hawaiian.jpg")));
                break;
            case "Mar y Tierra":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mar.jpg")));
                break;
            case "Clásica Americana":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clasica.jpg")));
                break;
            case "Bosque Blanco":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bosqueBlanco.jpg")));
                break;
            case "Veggie Deluxe":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deluxe.jpg")));
                break;
            case "Cheese Bomb":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg")));
                break;
            case "Fundición Suprema":
                lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suprema.jpg")));
                break;
            default:
                throw new AssertionError();
        }
        lblPrecioPizza.setText("$" + String.valueOf(detalle.getPizza().getPrecio()) + " MXN");
        lblCantidad.setText(String.valueOf(detalle.getCantidad()));
    }

    public void aumentarCantidadPedido() {
        detalle.setCantidad(detalle.getCantidad() + 1);
        lblCantidad.setText(String.valueOf(detalle.getCantidad()));
        cargarInfo();
        carrito.cargarPedidoTextArea();
    }

    public void disminuirCantidadPedido() {
        detalle.setCantidad(detalle.getCantidad() - 1);
        lblCantidad.setText(String.valueOf(detalle.getCantidad()));
        cargarInfo();
        carrito.cargarPedidoTextArea();
    }

    public void cargarInfo() {
        if (!(detalle.getCantidad() != 1)) {
            btnMenos.setVisible(false);
        } else {
            btnMenos.setVisible(true);
        }
    }

    public void eliminarPedido() {
        carrito.eliminarPanel(detalle);
        carrito.cargarPedidoTextArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombrePizza = new javax.swing.JLabel();
        lblPrecioPizza = new javax.swing.JLabel();
        btnMenos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 225, 218));

        btnEliminar.setBackground(new java.awt.Color(255, 43, 43));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        lblNombrePizza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombrePizza.setText("jLabel2");

        lblPrecioPizza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrecioPizza.setText("jLabel2");

        btnMenos.setBackground(new java.awt.Color(255, 255, 255));
        btnMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(234, 225, 218));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");

        javax.swing.GroupLayout btnMenosLayout = new javax.swing.GroupLayout(btnMenos);
        btnMenos.setLayout(btnMenosLayout);
        btnMenosLayout.setHorizontalGroup(
            btnMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        btnMenosLayout.setVerticalGroup(
            btnMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        btnMas.setBackground(new java.awt.Color(255, 255, 255));
        btnMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("+");

        javax.swing.GroupLayout btnMasLayout = new javax.swing.GroupLayout(btnMas);
        btnMas.setLayout(btnMasLayout);
        btnMasLayout.setHorizontalGroup(
            btnMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        btnMasLayout.setVerticalGroup(
            btnMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        lblCantidad.setBackground(new java.awt.Color(255, 255, 255));
        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioPizza)
                            .addComponent(lblNombrePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombrePizza)
                        .addGap(26, 26, 26)
                        .addComponent(lblPrecioPizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(Color.decode("#EA2929"));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(Color.decode("#FF2B2B"));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnMenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseEntered
        btnMenos.setBackground(Color.gray);    }//GEN-LAST:event_btnMenosMouseEntered

    private void btnMenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseExited
        btnMenos.setBackground(Color.white);
    }//GEN-LAST:event_btnMenosMouseExited

    private void btnMasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasMouseEntered
        btnMas.setBackground(Color.gray);
    }//GEN-LAST:event_btnMasMouseEntered

    private void btnMasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasMouseExited
        btnMas.setBackground(Color.white);
    }//GEN-LAST:event_btnMasMouseExited

    private void btnMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseClicked
        disminuirCantidadPedido();
    }//GEN-LAST:event_btnMenosMouseClicked

    private void btnMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasMouseClicked
        aumentarCantidadPedido();    }//GEN-LAST:event_btnMasMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        eliminarPedido();
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnMas;
    private javax.swing.JPanel btnMenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombrePizza;
    private javax.swing.JLabel lblPrecioPizza;
    // End of variables declaration//GEN-END:variables
}
