/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.vistas;

import Negocio.BOs.ICarritoBO;
import Negocio.BOs.IPedidoBO;
import Negocio.BOs.IPizzaBO;
import Negocio.DTOs.PizzaDTO;
import Negocio.Fabrica.FabricaBOs;
import java.awt.Color;
import presentacion.frmCatalogo;
import presentacion.frmDetallesPizza;

/**
 *
 * @author sando
 */
public class panTarjetasPizzas extends javax.swing.JPanel {

    private PizzaDTO pizzaFiltrada;
    private PizzaDTO pizza;
    private frmCatalogo catalogo;
    private int idUsuario;
    private String token;
    private boolean express;

    /**
     * Creates new form panTarjetasPizzas
     */
    public panTarjetasPizzas() {
        initComponents();
    }

    public void setDatosPizza(PizzaDTO pizzaFiltrada, frmCatalogo catalogo, int idUsuario) {
        this.catalogo = catalogo;
        this.idUsuario = idUsuario;
        this.pizzaFiltrada = pizzaFiltrada;
        lblNombre.setText(pizzaFiltrada.getNombre());
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + pizzaFiltrada.getRutaImagen())));
    }

    public void setDatosPizzaExpress(PizzaDTO pizzaFiltrada, frmCatalogo catalogo, String token) {
        this.catalogo = catalogo;
        this.token = token;
        this.express = true;
        this.pizzaFiltrada = pizzaFiltrada;

        lblNombre.setText(pizzaFiltrada.getNombre());
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + pizzaFiltrada.getRutaImagen())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnAnadir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 207, 175));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnAnadir.setBackground(new java.awt.Color(255, 92, 56));
        btnAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnadirMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("+Añadir");

        javax.swing.GroupLayout btnAnadirLayout = new javax.swing.GroupLayout(btnAnadir);
        btnAnadir.setLayout(btnAnadirLayout);
        btnAnadirLayout.setHorizontalGroup(
            btnAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAnadirLayout.setVerticalGroup(
            btnAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseClicked
        frmDetallesPizza frmPizza = new frmDetallesPizza();

        if (express) {
            frmPizza.cargarInformacionPizzaExpress(pizzaFiltrada, token);
        } else {
            frmPizza.cargarInformacionPizza(pizzaFiltrada, idUsuario);
        }

        frmPizza.setVisible(true);
        catalogo.dispose();
    }//GEN-LAST:event_btnAnadirMouseClicked

    private void btnAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseEntered
        btnAnadir.setBackground(Color.decode("#E82F07"));


    }//GEN-LAST:event_btnAnadirMouseEntered

    private void btnAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseExited
        btnAnadir.setBackground(Color.decode("#FF5C38"));
    }//GEN-LAST:event_btnAnadirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAnadir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
